### ISSUE TITLE
Research actual mathematical description of the problem

### ISSUE THREAD

**Issue by navima** [navima/satcalc#2]
Problem-resolution?
Dependency graph?
Constraint resolution?
What the fuck do we actually want?

**Comment by navima** [comment]
Findings:
Whether there is a known AI problem type that fits is still not known.
The actual description however, is fairly simple.

For every *Calculation*, we need to:
- Construct a graph, in which
  - Nodes are
    - Recipes (including alt recipes), with a Multiplier
    - Inputs (denoting items which cannot be created via a recipe, or which are explicitly listed in Inputs)
    - Outputs
  - Edges are Item connections
    - Source - the source node of the Edge
    - Target - the target node of the Edge
    - Item - the type of item the connection represents
    - Rate - the "number" of Items transported (number itself is also a rate: 1/minute, but this deosn't matter here)
  - To create this graph, we instantiate the Output nodes, then expand from there.
  Expanding a node is the following process: 
    - If node is Output
      - We instantiate all non-blocked Recipes that produce the item
    - If node is Recipe
      - For each input
        - We instantiate all non-blocked Recipes that produce the item
    - If node is Input, we leave it as is
- Calculate the Cost of each edge such that:
  - Cost of an edge is the cost of its source Node
  - Cost of a Node is
    - If node is Output, cost is undefined
    - If node is Input, cost is WP
    - If node is Recipe, cost is the minimum of the smallest subsets of all Edges targeting the Recipe that satisfy all its inputs, such that a Cost of an Edge set is the sum of the Costs of all Edges contained in the set
    - _Impl. note: to optimise, we could skip calculating the costs for a whole "subtree", once the minimal cost that is still being calculated becomes greater than another cost that is further down the tree._
- Prune
  - For each Recipe (starting with the ones closest to the Outputs)
    - Find the least Costly subset of Edges that satisfy the recipe. We will call this the optimal set
    - Remove all edges not contained in the optimal set
  - _Impl. note: We could consolidate this step into the previous one, so that when we know for sure that a solution is suboptimal, we just remove it entirely_
- Simplify
  - Find all the Recipe instances that are of the same class and merge them thusly:
    - The set of all Recipe instances of the same class will be called `R={r1,r2,...rn}`
    - Create a new Recipe instance `r`
      - Multiplier = sum of `R`'s Multipliers
    - Change the source of all outgoing Edges of all Nodes in `R` to `r`
    - Change the target of all incoming Edges of all Nodes in `R` to `r`
    - Remove `R`
    - Merge all affected edges of the same item if possible
      - Edges can be merged when their items, their sources and their targets are all identical
      - Merging a set of edges `E={e1,e2,...en}` is the following process:
        - Create a new Edge `e`
          - With the same item, source and target
          - Rate = sum of `E`'s Rates
        - Remove `E`
          -

**Comment by Errelian** [comment]
LGTM.
